### ISSUE TITLE
Actividad 2

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-2-infografia-Nancy-0714#1]
Actividad 2
Nancy Olivera Santiago.
Grupo: 1BS 

![Infografía-Nancy OliveraSantiago](https://user-images.githubusercontent.com/112412856/187828864-00f41c01-b586-416b-bff3-2bf3fdd9b26a.jpg)

**Comment by Daisy-GonzalezLita12** [comment]
18.6

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
